### ISSUE TITLE
アイコンをフォント形式にする？

### ISSUE THREAD

**Issue by S--Minecraft** [S--Minecraft/read.crx-2#19]
未確認のため確認必
高速化できるかもしれない

**Comment by S--Minecraft** [comment]
http://cappee.net/coding/web-icon

**Comment by S--Minecraft** [comment]
CSSスプライトも試す
http://instantsprite.com/

**Comment by S--Minecraft** [comment]
loading.svgのcss実装
```css
progress.circle {
  -webkit-appearance: none;
  position: relative;
  width: 100px;
  height: 100px;
  animation: rotateThis 1s ease infinite;
}
@keyframes rotateThis {
  0% {transform: rotate(-45deg);}
  100% {transform: rotate(315deg);}
}
progress.circle::-webkit-progress-bar {
  background-color: #eeeeee;
  border-radius: 50px;
}
progress.circle::-webkit-progress-bar::before {
  content: "";
  position: absolute;
  top: 0;
  right: 0;
  width: 50px;
  height: 50px;
  border-radius:0 50px 0 0;
  background-color: #999999;
}
progress.circle::-webkit-progress-bar::after {
  content: "";
  position: absolute;
  top: 10px;
  left: 10px;
  height: 80px;
  width: 80px;
  background-color: #ffffff;
  border-radius: 40px;
}
progress.circle:not([value])::-webkit-progress-value {
  background-color: rgba(0,0,0,0);
}
```
```html
<progress class="circle" max="100"></progress>
```

**Comment by S--Minecraft** [comment]
loading.svgのアニメーション部のみcss版
```css
img.rotate {
  animation: rotateThis 1.5s linear infinite;
}
@keyframes rotateThis {
  0% {transform: rotate(-45deg);}
  100% {transform: rotate(315deg);}
}
```
```html
<img class="rotate" src="loading.svg">
```
```svg
<?xml version="1.0" encoding="utf-8"?>
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="100" height="100">
  <path d="M20,50 a30,30 0 0 0 30,30" fill="none" stroke="#ccc" stroke-width="10" stroke-linecap="round"></path>
</svg>
```
